config/routes.rb
Thingsmattchandlersaid::Application.routes.draw do

  match 'query' => 'search#results'
  match 'search' => 'search#index'
  match 'recent' => 'search#recent'
  match 'queries' => 'search#queries'

  root :to => "search#index"
end

app/models/query.rb
class Query < ActiveRecord::Base
end

app/models/sermon.rb
class Sermon < ActiveRecord::Base
  def Sermon.to_title file_name
    ret = File.basename((file_name.split /_/)[-1], ".txt")

    ret.gsub(/::/, '/').
        gsub(/([A-Z]+)([A-Z][a-z])/,'\1 \2').
        gsub(/([a-z\d])([A-Z])/,'\1 \2')
  end

  def url
    "http://media.thevillagechurch.net/sermons/transcripts/#{filename}"
  end

  #thinking sphinx index generation for fields
  define_index do
    indexes title
    indexes content
    has published_date
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  respond_to :html, :xml, :json, :js

  def index
  end

  def results
    page = params[:page] || 1

    @search = params[:search]

    #update historic query table
    q = Query.find_by_query(@search.downcase)
    if q.nil?
      Query.create(:query => @search.downcase, :count => 1, :last_use => DateTime.now)
    else
      q.update_attributes(:count => q.count+1, :last_use => DateTime.now)
    end

    @results = Sermon.search params[:search],
		 	     :with => {:published_date => (DateTime.new(2006, 1, 1)..DateTime.now)},
			     :page => page,
			     :per_page => 10,
           :field_weights => { :title => 10, :content => 5}

    respond_with @results
  end

  def recent
    @sermons = Sermon.where("sermons.published_date >= '#{2.months.ago}'").order("sermons.published_date desc")
    respond_with @sermons
  end

  def queries
    @queries = Query.where("queries.last_use >= '#{1.month.ago}'").order("queries.count desc").limit(5)
    respond_with @queries
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def google_font_link_tag family
    tag 'link', {:rel => :stylesheet, :type => Mime::CSS, :href => "http://fonts.googleapis.com/css?family=#{family}"}, false, false
  end

  def google_analytics
    <<-END_SQL
      <script type="text/javascript">

      var _gaq = _gaq || [];
      _gaq.push(['_setAccount', 'UA-26223301-1']);
      _gaq.push(['_trackPageview']);

      (function() {
        var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
        ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
      })();

      </script>
    END_SQL
  end
end

app/views/layouts/_disclaimer.html.haml
= "** This site is in no way affiliated with "
= link_to('The Village Church', "http://thevillagechurch.com")
= "and/or the person of Matt Chandler. It is intended, by the "
= link_to('author', "http://twitter.com/tcopp") + ","
= "to be a resource to the community and for the glory of God."

app/views/layouts/application.html.haml
!!! html5
%html
  %head
    %title matt chandler said
    = stylesheet_link_tag :all
    = google_font_link_tag("PT Serif")
    = javascript_include_tag :defaults
    = csrf_meta_tag

    %body
      #disclaimer
        =render :partial => "layouts/disclaimer"
      #container.container_12

        #header.grid_12
          = render :partial => "layouts/header"

        #notification
          %p.notice= notice
          %p.alert= alert

        #content
          = yield

        #footer.grid_12
          = render :partial => "layouts/footer"

app/views/search/_option_queries.html.haml
%ul
  - list.each do |q|
    %li
      = link_to q.query, query_path(:search => q.query)

app/views/search/_option_recent.html.haml
%ul
  - list.each do |s|
    %li
      = s.published_date.strftime("%m.%d.%Y")
      = " | "
      = link_to s.title, s.url

app/views/search/_search_box.html.haml
- message ||= ""

#action_bar
  #title.grid_7
    %img{ :src => 'images/title.png' }

  #search.grid_7
    = form_tag '/query' do
      = text_field_tag 'search', @search, :class => "bar"
      = image_submit_tag '/images/search.png', :class => "icon"
  .clear
  - if message.empty?
    #options.grid_7
      %ul
        %li.recent= link_to "recently added", { :controller => "search", :action => "recent" }, :remote => true
        %li.recent= link_to "common searches", { :controller => "search", :action => "queries" }, :remote => true
    %br
    %br
    %div#info
  - else
    .grid_7.italic.message= message

app/views/search/index.html.haml
#front
  .grid_12
    = render :partial => "search/search_box"

app/views/search/queries.js.haml
:plain
  $('#info').slideUp('fast', function() {
    $(this).html('#{escape_javascript(render :partial => "search/option_queries", :locals => { :list => @queries })}');
    $(this).slideDown();
  });

app/views/search/recent.js.haml
:plain
  $('#info').slideUp('fast', function() {
    $(this).html('#{escape_javascript(render :partial => "search/option_recent", :locals => { :list => @sermons })}');
    $(this).slideDown();
  });

app/views/search/results.html.haml
#query
  = render :partial => "search/search_box", :locals => {:center => false, :message => "Found #{@results.total_entries} sermons."}

  .grid_8
    #results
      - @results.each_with_weighting do |r, weight|
        .result
          .date= r.published_date.strftime("%B %d %Y")
          %h3.title= link_to r.title, r.url
          %p= r.excerpts.content.html_safe

    = will_paginate @results, :class => "pagination", :params => { :search => @search }